services:
  frontend:
    build: 
      context: frontend
      args:
        - VITE_API_URL=$VITE_API_URL
    ports:
      - "3000:3000"
  backend:
    build: backend
    ports:
      - "5000:5000"
    volumes:
      - videos:/app/uploads
  ai:
    build: ai
    depends_on:
      - backend    
    volumes:
      - videos:/app/uploads
volumes:
  videos:

